### ISSUE TITLE
Maybe other License?

### ISSUE THREAD

**Issue by negue** [chromealex/Unity3d.UI.Windows#11]
Maybe its only me, but this GPL License bothered me since I started as a dev years ago.

Ofcouse OpenSource is good, but this license ...

As far as I understand it, every GUI / (or Game) which uses this Library would need to be open source too.

If this is your target audience then please close this issue.^^

If not, maybe something like MIT is a more common choice  (of the libraries I've seen).

Don't take it the wrong way, from what I've seen this library looks / works good, thats why I'd like to use it^^

**Comment by chromealex** [comment]
Hi,

Yes, the license was MIT in my mind and I'll change it in a few days. 

Thanks

**Comment by negue** [comment]
Great, thanks! :smile:

**Comment by chromealex** [comment]
MIT now
