### ISSUE TITLE
cant open graph editor

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#12]
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[UnityEngine.UI.Windows.Plugins.Flow.FlowWindow].get_Item (Int32 index) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
UnityEngine.UI.Windows.Plugins.Flow.FlowData.GetWindow (Int32 id) (at Assets/UI.Windows/Addons/Flow/Core/FlowData.cs:396)
UnityEngine.UI.Windows.Plugins.Flow.FlowSystem.GetWindow (Int32 id) (at Assets/UI.Windows/Addons/Flow/Core/FlowSystem.cs:168)
UnityEditor.UI.Windows.Plugins.Flow.FlowSystemEditorWindow.<DrawSettings>m__13 () (at Assets/UI.Windows/Addons/Flow/Core/Editor/Core/EditorWindow.cs:844)
UnityEditor.UI.Windows.Plugins.Flow.Flow.DrawModuleSettingsGUI (IWindowFlowAddon addon, System.String caption, UnityEditor.GenericMenu settingsMenu, System.Action onGUI) (at Assets/UI.Windows/Addons/Flow/Editor/FlowAddon.cs:98)
UnityEditor.UI.Windows.Plugins.Flow.FlowSystemEditorWindow.DrawSettings (Single offsetY) (at Assets/UI.Windows/Addons/Flow/Core/Editor/Core/EditorWindow.cs:842)
UnityEditor.UI.Windows.Plugins.Flow.FlowSystemEditorWindow.OnGUI () (at Assets/UI.Windows/Addons/Flow/Core/Editor/Core/EditorWindow.cs:186)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by ladon** [comment]
and this error 
ullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Windows.WindowSystem.ApplyToSettings (UnityEngine.Camera camera) (at Assets/UI.Windows/Core/WindowSystem.cs:320)
UnityEngine.UI.Windows.WindowBase.SetupCamera () (at Assets/UI.Windows/Core/WindowBase.cs:514)
UnityEngine.UI.Windows.WindowBase.OnValidate () (at Assets/UI.Windows/Core/WindowBase.cs:498)
UnityEngine.UI.Windows.Types.LayoutWindowType.OnValidate () (at Assets/UI.Windows/Types/Default/LayoutWindowType.cs:104)
UnityEditor.AssetDatabase:LoadAssetAtPath(String, Type)
ME.<GetPrefabsOfTypeRaw>c__AnonStorey43`1:<>m__9A() (at Assets/UI.Windows/Extensions/ME/EditorUtilities.cs:206)
ME.Utilities:CacheComponentsArray(Func`1, Boolean, String) (at Assets/UI.Windows/Extensions/ME/CacheUtilities.cs:23)
ME.EditorUtilities:GetPrefabsOfTypeRaw(Boolean, String, Boolean, Func`2) (at Assets/UI.Windows/Extensions/ME/EditorUtilities.cs:230)
ME.EditorUtilities:GetPrefabsOfType(Boolean, String, Boolean, Func`2) (at Assets/UI.Windows/Extensions/ME/EditorUtilities.cs:184)
UnityEditor.EditorApplication:Internal_CallDelayFunctions()

**Comment by chromealex** [comment]
Hi,

Try to reimport any *.cs file.

**Comment by chromealex** [comment]
This errors already fixed but I dont push them because of new features in 0.9.4a.

**Comment by ladon** [comment]
reimport dont help. im try open Ui.Flow graph view and get spam error.
wait new version

**Comment by chromealex** [comment]
Okey, it will be today.

**Comment by chromealex** [comment]
Try the new version, please.

**Comment by ladon** [comment]
Yes, works. But now I broke another piece. :)

**Comment by ladon** [comment]
close
