### ISSUE TITLE
Broken ui compilation

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#13]
Create window.
Create container.
Attach window to container.
Try compile UI. 
(error) Step 3 - Processing files does not end.
Unattach window from container. Destroy container.
Try compile UI. 
(error) Step 3 - Processing files does not end.

Destroy all
Create window.
Try compile UI. 
Works.

**Comment by ladon** [comment]
Update - second compilation UI does not end. So need change graph to compile.

**Comment by ladon** [comment]
And destroy window do not help compile UI. Need create another window.

**Comment by chromealex** [comment]
Is any errors in unity console while compile?

**Comment by ladon** [comment]
nop

**Comment by ladon** [comment]
error while create screen - NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Windows.Plugins.Flow.FlowDatabase.ReplaceComponents[FlowLayoutWindowTypeTemplate,WindowBase](UnityEngine.UI.Windows.Plugins.Flow.FlowLayoutWindowTypeTemplate source, System.Type withType) (at Assets/UI.Windows/Addons/Flow/Core/Editor/FlowDatabase.cs:70)
UnityEngine.UI.Windows.Plugins.Flow.FlowDatabase.GenerateScreen (System.String filepath, System.String className, UnityEngine.UI.Windows.Plugins.Flow.FlowLayoutWindowTypeTemplate template) (at Assets/UI.Windows/Addons/Flow/Core/Editor/FlowDatabase.cs:222)
UnityEditor.UI.Windows.Plugins.Flow.FlowChooserFilter+<CreateScreen>c__AnonStorey3.<>m__5 (UnityEngine.UI.Windows.Plugins.Flow.FlowLayoutWindowTypeTemplate element) (at Assets/UI.Windows/Addons/Flow/ChooserFilter/Editor/FlowChooserFilter.cs:188)
UnityEditor.UI.Windows.Plugins.Flow.FlowChooserFilterWindow+<Show>c__AnonStorey5`1[UnityEngine.UI.Windows.Plugins.Flow.FlowLayoutWindowTypeTemplate].<>m__A (UnityEngine.Component c) (at Assets/UI.Windows/Addons/Flow/ChooserFilter/Editor/FlowChooserFilterWindow.cs:78)
UnityEditor.UI.Windows.Plugins.Flow.FlowChooserFilterWindow.DrawComponents (Int32 xCount, Single width, Single height, UnityEngine.GUIStyle itemBox, UnityEngine.GUIStyle style) (at Assets/UI.Windows/Addons/Flow/ChooserFilter/Editor/FlowChooserFilterWindow.cs:302)
UnityEditor.UI.Windows.Plugins.Flow.FlowChooserFilterWindow.OnGUI () (at Assets/UI.Windows/Addons/Flow/ChooserFilter/Editor/FlowChooserFilterWindow.cs:219)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:185)
UnityEditor.HostView.Invoke (System.String methodName) (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:178)
UnityEditor.HostView.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/HostView.cs:74)

**Comment by chromealex** [comment]
Try to remove example flow project.

**Comment by chromealex** [comment]
I think the error was because of naming conflict.

**Comment by ladon** [comment]
Rebuilding Library because the asset database could not be found!
Removing Assets/UI.Windows/Addons/DevicePreview/Resources/UI.Windows/DevicePreview/Images/Apple because the asset does not exist
Removing Assets/UI.Windows/Addons/Flow/Example/ExampleProject/Gameplay/EndGame/Components because the asset does not exist
Removing Assets/UI.Windows/Addons/Flow/Example/ExampleProject/Gameplay/GameplayHUD/Components because the asset does not exist
Removing Assets/UI.Windows/Addons/Flow/Example/ExampleProject/Gameplay/GameplayView/Components because the asset does not exist

And  so on start clean project with Assets dir from git.

**Comment by chromealex** [comment]
You can remove Assets/UI.Windows/Addons/Flow/Example/ExampleProject folder
completely.
And ExampleProject.asset file too.

**Comment by chromealex** [comment]
Fixed in 0.9.6a
