### ISSUE TITLE
default namespace in Graph ( FlowData ) - wrong

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#14]
Create window. 
Get Assets/ProjecUi/Other/Window1Directory/Window1DirectoryScreen.cs(11,11): error CS1003: Syntax error, `.' expected

because 
namespace .UI.Other.Window1Directory {

why default namespace in Graph - .UI?
it is necessary to make the correct value

**Comment by chromealex** [comment]
Look through the left setting panel. Find Flow Compiler module and fill the
namespace field.

**Comment by ladon** [comment]
Yes, but why default value make pain to user?
it is necessary to set the value in the acceptable by default

**Comment by chromealex** [comment]
Yes, I'll fix it soon. Sorry about that, my system is in alpha only;)

**Comment by chromealex** [comment]
Fixed in 0.9.6a
