### ISSUE TITLE
create screen->layout from project dont work

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#15]
Create empty window from Graph. Try create screen from project menu and try create layout
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Windows.WindowSystem.ApplyToSettings (UnityEngine.Canvas canvas) (at Assets/UI.Windows/Core/WindowSystem.cs:355)
UnityEditor.UI.Windows.WindowLayoutEditor.Update_EDITOR (UnityEngine.UI.Windows.WindowLayout _target) (at Assets/UI.Windows/Layouts/Editor/WindowLayoutEditor.cs:393)
UnityEditor.UI.Windows.WindowLayoutEditor.UpdateLinks (UnityEngine.UI.Windows.WindowLayout _target) (at Assets/UI.Windows/Layouts/Editor/WindowLayoutEditor.cs:317)
UnityEditor.UI.Windows.WindowLayoutEditor.OnInspectorGUI () (at Assets/UI.Windows/Layouts/Editor/WindowLayoutEditor.cs:31)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean forceDirty, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect, Boolean eyeDropperDirty) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1162)
UnityEditor.DockArea:OnGUI()

**Comment by chromealex** [comment]
Be sure you have the latest version.
If so, be sure you have an Initializer on the currently opened scene.

**Comment by ladon** [comment]
initializer... the area is still unknown to me.
I will try to copy the example

**Comment by chromealex** [comment]
Fixed in 0.9.6a
