### ISSUE TITLE
basic example scene - need fix

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#16]
WindowSystem need ObjectPool reference
UnityEngine.UI.Windows.WindowSystem:Awake()

There's no normal documentation, so need to fix at least some examples.

**Comment by chromealex** [comment]
Oh yeah. I'll fix examples tomorrow. You can fix it by set ref in the
inspector.

**Comment by chromealex** [comment]
Fixed in 0.9.6a
