### ISSUE TITLE
Cant flow

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#19]
Create SplashScreen ( id 1) 
Create MainMenuScreen ( id 4)
Attach each to other
On tap in SplashCreen call FlowMainMenu.

from 1 to 4
UnityEngine.UI.Windows.Plugins.Flow.FlowSystem:GetAttachItem(Int32, Int32)
UI.Start.Splash.SplashScreenBase:INTERNAL_FlowMainMenu(Boolean, Action`1)

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Windows.Plugins.Flow.FlowSystem.GetAttachItem (Int32 from, Int32 to) (at Assets/UI.Windows/Addons/Flow/Core/FlowSystem.cs:104)
UI.Start.Splash.SplashScreenBase.INTERNAL_FlowMainMenu (Boolean hide, System.Action`1 onParametersPassCall) (at Assets/UI/UI/Start/Splash/SplashScreenBase.cs:44)
UI.Start.Splash.SplashScreenBase.FlowMainMenu () (at Assets/UI/UI/Start/Splash/SplashScreenBase.cs:25)
UI.Start.Splash.SplashScreen.OnTapHandler () (at Assets/UI/UI/Start/Splash/SplashScreen.cs:25)

**Comment by ladon** [comment]
Debug.Log ("FlowSystem.instance.data " + (FlowSystem.instance.data == null));
FlowSystem.instance.data True
???

**Comment by chromealex** [comment]
I think your FlowWindowsSystem on the scene not correct. Be sure it
contains your flow data.

**Comment by ladon** [comment]
in ExampleProject FlowData Windows has 17 elements and WindowAssets has 17 elements too
in my UI FlowData Windows 0 elements, but WindowAssets 3 elements...

**Comment by chromealex** [comment]
Windows was depricated. WindowAssets is the new one.

**Comment by chromealex** [comment]
Find FlowWindowSystem script on the scene. Check Flow Project section.

**Comment by ladon** [comment]
WindowSystem deprecated too?
Need use WindowSystemFlow?
in sample WindowSystemInitializer has WindowSystem. Am take this prefab as initializer...

**Comment by chromealex** [comment]
Sorry for an old example. I'll fix it tomorrow.

You need follow hierarchy at the scene:
WindowSystemFlow.cs
-- ObjectPool.cs
-- UnityEventSystem (here you can add HeatmapInputModule)
-- Events (WindowSystemInput)
-- Tweeners (GlobalTweener.cs, Tweener.cs (with game time), Tweener.cs
(with fixed time)).

**Comment by ladon** [comment]
Im flow finally! :)

**Comment by chromealex** [comment]
WindowsSystem - it's the core of my system.
You cam simply use it with raw windows list. But you can't use any "Flow"
methods.
WindowSystemFlow - it's an addon to the core. So, if you want to use UIW
Flow - use this initializer.

Example do not use Flow at all. It's use raw api methods like
WindowsSystem.Show()

**Comment by chromealex** [comment]
I'll do the new example that use flow methods tommorow.

**Comment by chromealex** [comment]
Added WindowSystemFlowInitializer prefab
