### ISSUE TITLE
strange FlowWindow

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#20]
Im attach/deattach windows in UIW Flow and get strange window.
Its invisible, in my hierarchy it looks as 0_ 
Id 0
rect  0 0 0 0
Compiled Dir/Namespace/ScreenName/Base class - empty field

But its try compile... im set Flags to Reserved1 for forbid compilation this window.
Its undeleteable. 
Earlier im set fields for 2 such window, then they show in grid and im can delete they.

How delete this strange window without black magic?

**Comment by chromealex** [comment]
Try to save Unity project (Ctrl+S or Cmd+S)

**Comment by chromealex** [comment]
Do not set Reserved flag. Set Default.
