### ISSUE TITLE
cant compile or destroy 0_ FlowWindow

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#21]
Somehow im get FlowWindow with name 0_
Cant destroy or handle with it.

Creating of new window make another 0_ name and do not show in UIW Flow window.
Compilation do nothig. If change id and save project afret recompile - rename 0_ to Id_+Title 
To view this window need change rect. 
But one 0_ still stay.

**Comment by chromealex** [comment]
Fixed in 1.0.0a version.
