### ISSUE TITLE
1.0.0a + unity 5.1.1

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#22]
Assets/UI.Windows/Components/Default/Advanced/Linker/Editor/LinkerComponentEditor.cs(36,72): error CS0122: `UnityEditor.SerializedObject.ApplyModifiedPropertiesWithoutUndo()' is inaccessible due to its protection level

**Comment by chromealex** [comment]
Try to upgrade Unity.
