### ISSUE TITLE
0.9.9a => 1.0.0a

### ISSUE THREAD

**Issue by ladon** [chromealex/Unity3d.UI.Windows#23]
Am overwrite Assets in my project, and get errors

Assets/UI.Windows/Components/Default/Basic/Buttons/Old/ButtonHoverComponent.cs(11,22): error CS0101: The namespace `UnityEngine.UI.Windows.Components' already contains a definition for`ButtonHoverComponent'

Assets/UI.Windows/Components/Default/Basic/Buttons/Old/ButtonWithImageComponent.cs(10,22): error CS0101: The namespace `UnityEngine.UI.Windows.Components' already contains a definition for`ButtonWithImageComponent'

Assets/UI.Windows/Components/Default/Basic/Buttons/Old/ButtonWithTextAndImageComponent.cs(10,22): error CS0101: The namespace `UnityEngine.UI.Windows.Components' already contains a definition for`ButtonWithTextAndImageComponent'

Assets/UI.Windows/Components/Default/Basic/Buttons/Old/ButtonWithTextComponent.cs(9,22): error CS0101: The namespace `UnityEngine.UI.Windows.Components' already contains a definition for`ButtonWithTextComponent'

**Comment by chromealex** [comment]
ButtonHover, ButtonWithImage, ButtonWithText, ButtonWithTextAndImage were
moved into Old folder. Check it. All of Old files were deprecated.

**Comment by ladon** [comment]
So need to delete them?  Mb delete files from git?

**Comment by chromealex** [comment]
In git it must be ok. Check them.
