### ISSUE TITLE
Many errors in Unity3d 5.3.4,,, AddScriptComponentUnchecked can't define...and so on

### ISSUE THREAD

**Issue by atgczcl** [chromealex/Unity3d.UI.Windows#27]
Scene: Components,  old scene are not work well

NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Windows.Components.Tabs.AddItem[ButtonComponent,WindowComponent](UnityEngine.UI.Windows.WindowComponent component, UnityEngine.Events.UnityAction`1 onClick, Boolean autoEvents) (at Assets/UI.Windows/Components/Default/Advanced/Tabs/Tabs.cs:50)
UIWindowExampleComponents.OnInit () (at Assets/UI.Windows/Examples/Old/Scripts/Components/UIWindowExampleComponents.cs:26)
UnityEngine.UI.Windows.WindowBase.Init (Single depth, Single zDepth, Int32 raycastPriority, Int32 orderInLayer) (at Assets/UI.Windows/Core/WindowBase.cs:189)
UnityEngine.UI.Windows.WindowBase.Init (UnityEngine.UI.Windows.WindowBase source, Single depth, Single zDepth, Int32 raycastPriority, Int32 orderInLayer) (at Assets/UI.Windows/Core/WindowBase.cs:121)
UnityEngine.UI.Windows.WindowSystem.CreateWithIgnore_INTERNAL (UnityEngine.UI.Windows.WindowBase source, System.Action`1 onParametersPassCall, System.Boolean& ignoreActions, System.Object[] parameters) (at Assets/UI.Windows/Core/WindowSystem.cs:1054)
UnityEngine.UI.Windows.WindowSystem.Create_INTERNAL (UnityEngine.UI.Windows.WindowBase source, System.Action`1 onParametersPassCall, System.Object[] parameters) (at Assets/UI.Windows/Core/WindowSystem.cs:1021)
UnityEngine.UI.Windows.WindowSystem.GetInstance (UnityEngine.UI.Windows.WindowBase window, System.Object[] parameters) (at Assets/UI.Windows/Core/WindowSystem.cs:792)
UnityEngine.UI.Windows.WindowSystem.ShowDefault_INTERNAL (System.Object[] parameters) (at Assets/UI.Windows/Core/WindowSystem.cs:772)
UnityEngine.UI.Windows.WindowSystem.ShowDefault (System.Object[] parameters) (at Assets/UI.Windows/Core/WindowSystem.cs:764)
UIWindowExampleStart.Start () (at Assets/UI.Windows/Examples/Old/Scripts/Basic/UIWindowExampleStart.cs:17)

NullReferenceException: (null)
UnityEditor.SerializedObject..ctor (UnityEngine.Object[] objs) (at C:/buildslave/unity/build/artifacts/generated/common/editor/SerializedPropertyBindings.gen.cs:74)
UnityEditor.Editor.GetSerializedObjectInternal () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorBindings.gen.cs:154)
UnityEditor.Editor.get_serializedObject () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorBindings.gen.cs:147)
UnityEditor.UI.CanvasScalerEditor.OnEnable () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEditor.UI/UI/CanvasScalerEditor.cs:48)

**Comment by chromealex** [comment]
Thank you for the issue.
Try it now.
