### ISSUE TITLE
`BaseMeshEffect' could not be found

### ISSUE THREAD

**Issue by franklzt** [chromealex/Unity3d.UI.Windows#28]
Assets/UI.Windows/Extensions/ME/UI/BaseVertexEffect.cs(8,50): error CS0246: The type or namespace name `BaseMeshEffect' could not be found. Are you missing a using directive or an assembly reference?

Assets/UI.Windows/Extensions/3rdParty/UI/CurvedText.cs(8,35): error CS0246: The type or namespace name `BaseMeshEffect' could not be found. Are you missing a using directive or an assembly reference?

Assets/UI.Windows/Extensions/3rdParty/UI/CylinderText.cs(9,37): error CS0246: The type or namespace name `BaseMeshEffect' could not be found. Are you missing a using directive or an assembly reference?

Assets/UI.Windows/Extensions/3rdParty/UI/UIFlippable.cs(8,51): error CS0246: The type or namespace name `IMeshModifier' could not be found. Are you missing a using directive or an assembly reference?

**Comment by franklzt** [comment]
Noted this project is base on Unity 5. Thanks

**Comment by chromealex** [comment]
What version of Unity do you use? 5.0? Or may be 5.3? (Last is 5.3.5)

**Comment by franklzt** [comment]
Using 5.4 beta 17 for testing. 

By the way, there lacks the documentation. Very hard to figures out what exactly this system is.
by using the editor to generate the UI code ?

By using 5.4 beta 17, if I open the preview window and then enter play mode. see the issue below:

UnityException: Load is not allowed to be called from a ScriptableObject constructor (or instance field initializer), call it in OnEnable instead. Called from ScriptableObject 'DevicePreviewWindow'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEngine.Resources.Load[GUISkin](System.String path) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/ResourcesBindings.gen.cs:59)
UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreviewWindow+Styles..ctor () (at Assets/UI.Windows/Addons/DevicePreview/Core/Editor/DevicePreviewWindow.cs:35)
UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreviewWindow..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for UnityEditor.UI.Windows.Plugins.DevicePreview.DevicePreviewWindow
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.

**Comment by chromealex** [comment]
You need UI.Flow window to build your project. The system is screen-based architecture for ui with code auto-generation with layouts abstruction. I can help with your project if you need.

**Comment by franklzt** [comment]
Would you please write one basic tutorial for the working flow ? I know how to setup the project, but do not know how to add the ui element and how can I preview the project ?

**Comment by chromealex** [comment]
Do you have an example flow project?

**Comment by franklzt** [comment]
I see the example project.
It sees there coding require to draw the UI.

**Comment by chromealex** [comment]
Coding is required if you want to make your events bindings, but my system have simple API to do this.
