### ISSUE TITLE
Errors in Unity 5

### ISSUE THREAD

**Issue by dakkuuan** [chromealex/Unity3d.UI.Windows#29]
I'm getting a whole host of errors in unity 5.  I'm not exactly sure what the issue is, these show up in your basic example.  I'd really like to use this for my project, since my game is mainly UI being the type of rpg it is, but if I have to go back to a different version of unity, I will.  
![unity5errors](https://cloud.githubusercontent.com/assets/19769601/15811746/2b0d7da8-2b7a-11e6-903a-06630d75a060.PNG)

**Comment by chromealex** [comment]
Hi. Give me a day to fix this.

**Comment by dakkuuan** [comment]
Thank you for the fast reply =)

**Comment by chromealex** [comment]
Try to create new directory and download zip source from github.
Then open it in unity.

2016-06-06 10:49 GMT+03:00 dakkuuan notifications@github.com:
