### ISSUE TITLE
Is this usable?

### ISSUE THREAD

**Issue by jwvanderbeck** [chromealex/Unity3d.UI.Windows#33]
This looks very interesting so I grabbed the source to give it a try.  Unfortunately it is just throwing tons of errors inside of Unity and while some pieces seem to work, I couldn't follow the QuickStart because of the errors.  The source files don't even look like valid code in many places unless they are somehow dynamically modified?

As an example:

``namespace .Other.Window1Directory {``

There is a That Namespace starts with a dot, and almost all the functions in that file do as well.  The code won't even compile.

So I feel like i'm missing something here and just curious if this is usable in tis current state or not?

**Comment by chromealex** [comment]
Hi!

Yes, it is usable and I use this every day.
May be some points in basic setup was miss, so unity spam with errors.
Can you give me your unity version so I'll check it on yours.

Thanks

**Comment by jwvanderbeck** [comment]
Using Unity 5.6.0f3

I just downloaded the source zip from GitHub, unzipped it, and opened it in Unity.  It had to upgrade from 5.5 but seemed ok.  So then I started following your example docs.  The UI Flow window looked a bit different but I figured the docs were just out of date, so I started following as best I could.  I created two windows ok, and attached them.  I then did the compile and that seemed ok.  Next I clicked the Create Screen button in the first UI and that was when Unity started spitting out tons of errors in the console and I couldn't seem to go any farther.

I'm attaching the log.


[EditorLog.txt](https://github.com/chromealex/Unity3d.UI.Windows/files/1049725/EditorLog.txt)

**Comment by chromealex** [comment]
Do you have Team Viewer? I can try to fix it for you.

2017-06-03 19:51 GMT+03:00 jwvanderbeck <notifications@github.com>:

**Comment by jwvanderbeck** [comment]
No I do not.  Do you have some idea what might be wrong?  Maybe Unity's upgrade broke everything?

**Comment by chromealex** [comment]
Yes, all was ok with Unity 5.5, but 5.6 I have not tested yet. I think I'll
check it in a hour and push some changes.

**Comment by chromealex** [comment]
Look into `quick start` guide, I rewrote some steps :)

2017-06-03 21:06 GMT+03:00 Alex Feer <chrome.alex@gmail.com>:
